#include <iostream>
#include <vector>
#define ll long long

using namespace std;


struct point{
    ll x, y;
};
struct ivl{
    int beg, end;
}


using vec = vector<point>;

// Segment tree. Code generated by ai.
static int segtree_n;

/* Build */
vector<ll> build_max_y_segment_tree(const vec& points) {
    segtree_n = points.size();
    vector<ll> segtree(4 * segtree_n);

    function<void(int, int, int)> build = [&](int idx, int l, int r) {
        if (l == r) {
            segtree[idx] = points[l].y;
            return;
        }
        int mid = (l + r) / 2;
        build(2 * idx, l, mid);
        build(2 * idx + 1, mid + 1, r);
        segtree[idx] = max(segtree[2 * idx], segtree[2 * idx + 1]);
    };

    if (segtree_n > 0)
        build(1, 0, segtree_n - 1);

    return segtree;
}

/* Hidden query */
ll query_max_y_internal(
    const vector<ll>& segtree,
    int idx, int l, int r,
    int ql, int qr
) {
    if (qr < l || r < ql)
        return LLONG_MIN;

    if (ql <= l && r <= qr)
        return segtree[idx];

    int mid = (l + r) / 2;
    return max(
        query_max_y_internal(segtree, 2 * idx, l, mid, ql, qr),
        query_max_y_internal(segtree, 2 * idx + 1, mid + 1, r, ql, qr)
    );
}

/* Query */
ll query_max_y(const vector<ll>& segtree, int left, int right) {
    return query_max_y_internal(
        segtree,
        1,                 // root
        0, segtree_n - 1,   // full range
        left, right
    );
}


void read_data(int& n, ll& U, vec& seq){
    cin >> n >> U;
    for(int i = 0 ; i < n ; i++){
        ll x, y;
        cin >> x >> y;
        seq.push_back({x, y});
    }
}

vector<ivl> dp(const int n, const int U, const vec& seq, const vector<ll>& seg_tree){
    vector<ivl> res(n);
    int k = 1;
    for(int i = 0 ; i < n ; ++i){
        res[i] = {i, k};
        ll Max = query_max_y(seg_tree, i, k);
        while(k < n - 1 && U_strict(k + 1, seq[k + 1], Max, U)){
            k++;
            Max = query_max_y(seg_tree, i, k);
        }
    }
}

void solve(){
    int n;
    ll U;
    vec seq;
    vec seg_tree;
    read_data(n, U, seq, seg_tree);
}

int main(){

}